<?php
Tạo mới
 "datapost" : 
{
	"action" :  1,
	"connected" : "4",
	"questionid_10" : 10,
	"questionid_11" : 11,
	"questionid_2" :  2,
	"questionid_1" :  1,
	"questionid_5" :  5,
	"questionid_7" :  7,
	"answer10" :  "3",
	"answer11" :  "3" ,
	"answer2" :  "3" ,
	"answer1" :  "3" ,
	"subnote10" :  "ha", 
	"subnote11" :  "ha" ,
	"subnote2" :  "ha" ,
	"subnote1" :  "ha" ,
"note" :  "note" },
"dataaccount" : {
	"ObjID" :  1024016402,
	"ContractNum" :  "SGD621262", 
	"ContractDate" :  "08-05-2016 12:00:00",
	"CustomerName" :  "Le Thi Mai" ,
	"Passport" :  "370611991" ,
	"CompanyName" : null,
	"CertificateNumber" : null,
	"Address" :  "TO1 DAY OC, P.Vinh Hiep, TP.Rach Gia, Kien Giang", 
	"BillTo" :  "TO1 DAY OC, P.Vinh Hiep, TP.Rach Gia, Kien Giang" ,
	"ContractType" :  196,
	"ContractTypeName" :  "ADSL - F6", 
	"ContractStatus" :  1,
	"ContractStatusName" :  "Binh thuong" ,
	"LoginName" :  "Kgdsl-160508-127" ,
	"Email" :  "" ,
	"Location" :  "KGG - Kien Giang" ,
	"Region" :  "Mien Nam" ,
	"LocationID" :  77,
	"BranchCode" :  0,
	"Suspend_Date" : null,
	"Suspend_Reason" : null,
	"ObjAddress" :  "TO1 DAY OC, P.Vinh Hiep, TP.Rach Gia, Kien Giang", 
	"LegalEntityName" :  "FPT" ,
	"PartnerName" :  "Khong co" ,
	"EocName" :  "Eoc" ,
	"FeeLocalType" :  "ADSL - F6" ,
	"Description" :  "" ,
	"Birthday" :  "1970-01-01 00:00:00" ,
	"Sex" :  0,
	"AccountSale" :  "KGG.HUYttk" ,
	"PackageSal" :  "VOD HD" ,
	"AccountINF" :  "phuongtay.diend" ,
	"FinishDateINF" :  "17-05-2016 07:45:47" ,
	"CenterINF" :  "TIN/PNC" ,
	"AccountList" : null,
	"FinishDateList" : null,
	"CenterList" : null,
	"Phone" :  "01235364044" ,
	"PaymentType" :  "Tai dia chi cua khach hang" ,
	"AccountPayment" : null,
	"SubParentDesc" :  "Vung 7" ,
	"UseService" :  3,
	"EmailINF" :  "phuongnam.diend@fpt.net" ,
	"EmailList" : null,
	"EmailSale" :  "LinhTTK4@fpt.com.vn" ,
	"KindDeploy" :  "Internet + IPTV" ,
	"KindMain" : null,
	"Supporter" :  "Indo", 
	"SubSupporter" :  "02" ,
	"AccountListINDO" : null
},
"surveyid" :  1,
"idS" :  "" ,
"arrayAnswer" :  "" ,
"codes" :  "86767" ,
"time_start" :  "2016-06-08 13:49:17"}

Retry
{
    "name":"huydp",
  "datapost" : {
      "note" :  "haha" ,
      "action" :  1,
      "connected" :  "4" ,
      "questionid_10" :  10,
      "questionid_11" :  11,
      "questionid_2" :  2,
      "questionid_1" :  1,
      "questionid_5" :  5,
      "questionid_7" :  7,
      "answer10" :  "3" ,
      "answer11" :  "3" ,
      "answer2" :  "3" ,
      "answer1" :  "3" },
  "dataaccount" : {
      "ObjID" :  1024016402,
      "ContractNum" :  "SGD621262" ,
      "ContractDate" :  "08-05-2016 12:00:00" ,
      "CustomerName" :  "Le Thi Mai" ,
      "Passport" :  "370611991" ,
      "CompanyName" : null,
      "CertificateNumber" : null,
      "Address" :  "TO1 DAY OC, P.Vinh Hiep, TP.Rach Gia, Kien Giang" ,
      "BillTo" :  "TO1 DAY OC, P.Vinh Hiep, TP.Rach Gia, Kien Giang" ,
      "ContractType" :  196,
      "ContractTypeName" :  "ADSL - F6" ,
      "ContractStatus" :  1,
      "ContractStatusName" :  "Binh thuong" ,
      "LoginName" :  "Kgdsl-160508-127" ,
      "Email" :  "" ,
      "Location" :  "KGG - Kien Giang" ,
      "Region" :  "Mien Nam" ,
      "LocationID" :  77,
      "BranchCode" :  0,
      "Suspend_Date" : null,
      "Suspend_Reason" : null,
      "ObjAddress" :  "TO1 DAY OC, P.Vinh Hiep, TP.Rach Gia, Kien Giang" ,
      "LegalEntityName" :  "FPT" ,
      "PartnerName" :  "Khong co" ,
      "EocName" :  "Eoc" ,
      "FeeLocalType" :  "ADSL - F6" ,
      "Description" :  "" ,
      "Birthday" :  "1970-01-01 00:00:00" ,
      "Sex" :  0,
      "AccountSale" :  "KGG.HUYttk" ,
      "PackageSal" :  "VOD HD" ,
      "AccountINF" :  "phuongtay.diend" ,
      "FinishDateINF" :  "17-05-2016 07:45:47" ,
      "CenterINF" :  "TIN/PNC" ,
      "AccountList" : null,
      "FinishDateList" : null,
      "CenterList" : null,
      "Phone" :  "01235364044" ,
      "PaymentType" :  "Tai dia chi cua khach hang" ,
      "AccountPayment" : null,
      "SubParentDesc" :  "Vung 7" ,
      "UseService" :  3,
      "EmailINF" :  "phuongnam.diend@fpt.net" ,
      "EmailList" : null,
      "EmailSale" :  "LinhTTK4@fpt.com.vn" ,
      "KindDeploy" :  "Internet + IPTV" ,
      "KindMain" : null,
      "Supporter" :  "Indo" ,
      "SubSupporter" :  "02" ,
      "isCheckList" :  0,
      "AccountListINDO" : null},
  "surveyid" :  1,
  "idS" :  "198644" ,
  "arrayAnswer" :  "10 11 2 1 "}